# Generated by Django 5.0.6 on 2026-05-29 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('timezone', models.CharField(default='UTC', max_length=60)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.PositiveIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25)),
                ('default_dork_engine', models.CharField(choices=[('google', 'Google'), ('bing', 'Bing'), ('duckduckgo', 'DuckDuckGo')], default='google', max_length=20)),
                ('auto_open_results', models.BooleanField(default=False)),
                ('shodan_api_key', models.CharField(blank=True, default='', max_length=200)),
                ('censys_api_id', models.CharField(blank=True, default='', max_length=200)),
                ('censys_api_secret', models.CharField(blank=True, default='', max_length=200)),
                ('virustotal_api_key', models.CharField(blank=True, default='', max_length=200)),
                ('github_api_key', models.CharField(blank=True, default='', max_length=200)),
                ('securitytrails_api_key', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
