# Generated by Django 5.0.6 on 2026-05-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('author', models.CharField(blank=True, default='', max_length=500)),
                ('producer', models.CharField(blank=True, default='', max_length=500)),
                ('creator', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('keywords', models.TextField(blank=True, default='')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('emails_csv', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_results', to='targets.target')),
            ],
            options={
                'verbose_name_plural': 'Metadata results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, default='', max_length=255)),
                ('powered_by', models.CharField(blank=True, default='', max_length=255)),
                ('cms', models.CharField(blank=True, default='', max_length=255)),
                ('cdn', models.CharField(blank=True, default='', max_length=255)),
                ('waf', models.CharField(blank=True, default='', max_length=255)),
                ('frameworks', models.CharField(blank=True, default='', max_length=500)),
                ('analytics', models.CharField(blank=True, default='', max_length=500)),
                ('js_libraries', models.CharField(blank=True, default='', max_length=500)),
                ('cookies', models.CharField(blank=True, default='', max_length=500)),
                ('meta_tags', models.TextField(blank=True, default='')),
                ('raw_headers', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='targets.target')),
            ],
        ),
        migrations.CreateModel(
            name='WHOISInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar', models.CharField(blank=True, default='', max_length=255)),
                ('creation_date', models.CharField(blank=True, default='', max_length=255)),
                ('expiration_date', models.CharField(blank=True, default='', max_length=255)),
                ('name_servers', models.TextField(blank=True, default='')),
                ('emails', models.TextField(blank=True, default='')),
                ('org', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('raw_data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whois', to='targets.target')),
            ],
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=10)),
                ('value', models.TextField()),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='targets.target')),
            ],
            options={
                'ordering': ['record_type', 'value'],
                'indexes': [models.Index(fields=['target', 'record_type'], name='recon_dnsre_target__0880be_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='targets.target')),
            ],
            options={
                'ordering': ['host'],
                'unique_together': {('target', 'host')},
            },
        ),
        migrations.CreateModel(
            name='WaybackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('timestamp', models.CharField(max_length=20)),
                ('status_code', models.CharField(blank=True, default='', max_length=10)),
                ('mime_type', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wayback_entries', to='targets.target')),
            ],
            options={
                'verbose_name_plural': 'Wayback entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target', '-timestamp'], name='recon_wayba_target__e46f54_idx')],
            },
        ),
    ]
