# Generated by Django 5.0.6 on 2026-05-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techresult',
            name='server_software',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='EmailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(blank=True, default='harvester', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='targets.target')),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('target', 'email')},
            },
        ),
        migrations.CreateModel(
            name='PortScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('state', models.CharField(default='open', max_length=20)),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_scans', to='targets.target')),
            ],
            options={
                'ordering': ['port'],
                'unique_together': {('target', 'port')},
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('subject_cn', models.CharField(blank=True, default='', max_length=255)),
                ('issuer_cn', models.CharField(blank=True, default='', max_length=255)),
                ('org', models.CharField(blank=True, default='', max_length=255)),
                ('san', models.TextField(blank=True, default='')),
                ('not_before', models.CharField(blank=True, default='', max_length=100)),
                ('not_after', models.CharField(blank=True, default='', max_length=100)),
                ('expires', models.CharField(blank=True, default='', max_length=100)),
                ('remaining_days', models.IntegerField(blank=True, null=True)),
                ('serial', models.CharField(blank=True, default='', max_length=100)),
                ('signature_algorithm', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certs', to='targets.target')),
            ],
            options={
                'ordering': ['port'],
                'unique_together': {('target', 'port')},
            },
        ),
    ]
