# Generated by Django 5.0.6 on 2026-05-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_remove_portscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techresult',
            name='target',
        ),
        migrations.RemoveField(
            model_name='waybackentry',
            name='target',
        ),
        migrations.RemoveField(
            model_name='whoisinfo',
            name='target',
        ),
        migrations.DeleteModel(
            name='MetadataResult',
        ),
        migrations.DeleteModel(
            name='TechResult',
        ),
        migrations.DeleteModel(
            name='WaybackEntry',
        ),
        migrations.DeleteModel(
            name='WHOISInfo',
        ),
    ]
