# Generated by Django 5.0.6 on 2026-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('full', 'Full Report'), ('subdomains', 'Subdomains'), ('dns', 'DNS Records'), ('dorks', 'Saved Dorks')], default='full', max_length=20),
        ),
    ]
