GOOGLE_DORKS = {
    "File Types": [
        "site:{domain} filetype:pdf",
        "site:{domain} filetype:doc",
        "site:{domain} filetype:docx",
        "site:{domain} filetype:xls",
        "site:{domain} filetype:xlsx",
        "site:{domain} filetype:ppt",
        "site:{domain} filetype:pptx",
        "site:{domain} filetype:csv",
        "site:{domain} filetype:xml",
        "site:{domain} filetype:json",
        "site:{domain} filetype:sql",
        "site:{domain} filetype:env",
        "site:{domain} filetype:conf",
        "site:{domain} filetype:log",
    ],
    "Login Portals": [
        "site:{domain} inurl:login",
        "site:{domain} inurl:signin",
        "site:{domain} inurl:auth",
        "site:{domain} intitle:login",
        "site:{domain} intitle:\"sign in\"",
        "site:{domain} inurl:wp-login",
        "site:{domain} inurl:admin/login",
    ],
    "Admin Panels": [
        "site:{domain} intitle:admin",
        "site:{domain} inurl:admin",
        "site:{domain} inurl:dashboard",
        "site:{domain} inurl:controlpanel",
        "site:{domain} inurl:cpanel",
        "site:{domain} intitle:\"control panel\"",
        "site:{domain} intitle:\"web console\"",
    ],
    "Open Directories": [
        "site:{domain} intitle:index.of",
        "site:{domain} intitle:\"index of /\"",
        "site:{domain} inurl:uploads",
        "site:{domain} inurl:backup",
        "site:{domain} inurl:storage",
        "site:{domain} inurl:files",
    ],
    "Backup & Config": [
        "site:{domain} inurl:backup",
        "site:{domain} ext:bak",
        "site:{domain} ext:old",
        "site:{domain} ext:swp",
        "site:{domain} ext:config",
        "site:{domain} ext:cfg",
    ],
    "Exposed Secrets": [
        "site:pastebin.com {domain}",
        "site:{domain} intext:password",
        "site:{domain} intext:api_key",
        "site:{domain} intext:secret",
        "site:{domain} intext:token",
        "site:{domain} intext:.env",
        "\"{domain}\" password",
        "\"{domain}\" api_key",
        "\"{domain}\" secret_key",
        "\"{domain}\" access_token",
        "\"{domain}\" database_url",
        "\"{domain}\" jwt_secret",
    ],
    "SQL & Errors": [
        "site:{domain} intext:\"sql syntax\"",
        "site:{domain} intext:\"mysql_fetch\"",
        "site:{domain} intext:\"ora-\"",
        "site:{domain} intext:\"warning: mysql\"",
        "site:{domain} intext:\"pg_dump\"",
        "site:{domain} intext:\"stack trace\"",
        "site:{domain} intext:\"fatal error\"",
    ],
    "Paste & Leak Sites": [
        "site:pastebin.com {domain}",
        "site:gist.github.com {domain}",
        "site:ghostbin.com {domain}",
        "site:justpaste.it {domain}",
        "site:rentry.co {domain}",
    ],
    "Index Pages": [
        "site:{domain} intitle:\"Apache\" \"Server at\"",
        "site:{domain} intitle:\"nginx\" \"index\"",
        "site:{domain} intitle:\"IIS\" \"Welcome\"",
        "site:{domain} intitle:\"directory listing\"",
    ],
    "Subdomain Hunting": [
        "site:*.{domain}",
        "site:dev.{domain}",
        "site:test.{domain}",
        "site:staging.{domain}",
        "site:api.{domain}",
        "site:admin.{domain}",
        "site:mail.{domain}",
    ],
}

GITHUB_DORKS = {
    "Secrets & Keys": [
        "\"{domain}\" password",
        "\"{domain}\" api_key",
        "\"{domain}\" secret_key",
        "\"{domain}\" access_token",
        "\"{domain}\" private_key",
        "\"{domain}\" ssh_key",
        "\"{domain}\" pem",
        "\"{domain}\" -----BEGIN",
    ],
    "Cloud Providers": [
        "\"{domain}\" aws_access_key",
        "\"{domain}\" aws_secret_key",
        "\"{domain}\" s3_bucket",
        "\"{domain}\" AZURE_CLIENT_ID",
        "\"{domain}\" GOOGLE_APPLICATION_CREDENTIALS",
        "\"{domain}\" GCP_PROJECT",
    ],
    "Tokens & JWT": [
        "\"{domain}\" token",
        "\"{domain}\" jwt",
        "\"{domain}\" bearer",
        "\"{domain}\" oauth",
        "\"{domain}\" refresh_token",
    ],
    "Database Secrets": [
        "\"{domain}\" DATABASE_URL",
        "\"{domain}\" mongodb",
        "\"{domain}\" postgresql",
        "\"{domain}\" mysql_host",
        "\"{domain}\" REDIS_URL",
    ],
    "Config Files": [
        "filename:.env {domain}",
        "filename:.env.prod {domain}",
        "filename:.env.staging {domain}",
        "filename:config.json {domain}",
        "filename:config.php {domain}",
        "filename:settings.py {domain}",
        "filename:secrets.yml {domain}",
    ],
    "Endpoints & Internal": [
        "\"{domain}\" localhost",
        "\"{domain}\" \"http://localhost\"",
        "\"{domain}\" \"internal\"",
        "\"{domain}\" \"10.0.\"",
        "\"{domain}\" \"192.168.\"",
    ],
}
